#ifndef NITROBTX_ERRORS_H
#define NITROBTX_ERRORS_H

enum ErrorCode {
    ERR_CODE_OK,
    ERR_CODE_OPTION_PARSE_FAILURE,
    ERR_CODE_FAILED_OPEN_INPUT,
    ERR_CODE_FAILED_OPEN_OUTPUT,
    ERR_CODE_INVALID_FILE_TYPE,
    ERR_CODE_INPUT_INVALID,
    ERR_CODE_UNSUPPORTED,
    ERR_CODE_UNSUPPORTED_FORMAT,
    ERR_CODE_LIBPNG_ERROR,
    ERR_CODE_RES_TREE_BUILD_FAIL,
};

#endif // NITROBTX_ERRORS_H
